### ISSUE TITLE
Workflow to auto close and lock PRs that match the `Update Readme.md` pattern

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#213]
How about this?

literal match the PR title, lock and close, post a comment with issue to explain the situation
would close [all these](https://github.com/expressjs/express/pulls?q=is%3Apr+%22Update+Readme.md%22+in%3Atitle) that we still have been getting. Github nuked some number of these initially right? Idk how many there were at the peak

With only 2 PRs that use default edit from web commit message having been landed in over 10 years, I don’t think we run a big risk of this locking genuine PRs that happen to use the default web commit message 

```yaml
name: Close and Lock Readme Update PRs

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  close-and-lock-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        id: check-title
        run: |
          if [[ "${{ github.event.pull_request.title }}" == "Update Readme.md" ]]; then
            echo "MATCHED=true" >> $GITHUB_ENV
          fi
      - name: Close PR
        if: env.MATCHED == 'true'
        uses: peter-evans/close-pull@v1
        with:
          comment: >
            Thank you for your contribution! Unfortunately, this PR has been closed because it appears to be a part of a common mistake originating from a tutorial.

            Please see Issue #123 for more information and guidance on how to contribute properly to this project.

            We appreciate your understanding and look forward to your future contributions!
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lock PR
        if: env.MATCHED == 'true'
        uses: peter-evans/lock-threads@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          lock-reason: "resolved"
          token: ${{ secrets.GITHUB_TOKEN }}
```
