### ISSUE TITLE
CITGM style ci for direct express deps

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#304]
Have we discussed this before?

CI job in direct dep repos we own which run express tests against changes to the package. 

Not as a blocker on merge of course, but as a quick heads up to signal if a change would break something in express. For both the submitter and the reviewer. 

This thought is inspired by discussions in tc chat about greater maintainer autonomy and change awareness in the individual packages. 

Independent of that topic, I see value in CITGM style tests. 

It would of course likely fail when working on a package major not being used by the express version being tested against.

**Comment by jonchurch** [comment]
```yml
name: Express Dependency Monitor (EDM)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-express-with-local-package:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allows the workflow to continue even if this job fails

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build package
      run: npm run build

    - name: Get package name from package.json
      id: pkg
      run: |
        echo "package_name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT

    - name: Pack local package
      run: npm pack
      shell: bash

    - name: Store package file name
      id: packfile
      run: |
        echo "packfile_name=$(ls *.tgz)" >> $GITHUB_OUTPUT

    - name: Clone Express.js
      run: git clone https://github.com/expressjs/express.git

    - name: Install Express.js dependencies
      run: |
        cd express
        npm install

    - name: Install local package into Express.js
      run: |
        cd express
        npm install ../${{ steps.packfile.outputs.packfile_name }}

    - name: Run Express.js tests
      run: |
        cd express
        npm test

```
