### ISSUE TITLE
Using GitHub CI/Actions

### ISSUE THREAD

**Issue by wesleytodd** [expressjs/discussions#88]
As mentioned in the last TC meeting, we are going to try out using GH actions for CI and automation stuff.  I pushed the statusboard repo last night, and added a workflow config to test it.  Here is an example run, in this case with passes and a failure:

PR: https://github.com/expressjs/statusboard/pull/1
Failure: https://github.com/expressjs/statusboard/pull/1/checks?check_run_id=194817152
Pass: https://github.com/expressjs/statusboard/pull/1/checks?check_run_id=194817160

Example failure email:

<img width="916" alt="Screen Shot 2019-08-15 at 3 47 00 PM" src="https://user-images.githubusercontent.com/1027776/63131853-00150580-bf74-11e9-985a-414b8ea40b64.png">

The workflow is a yaml file `.github/workflows/test.yml` with the following contents:

```
name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm it
```

I just wanted to post this here to see if anyone had concerns of feedback before I start expanding this automation.
